#!/usr/bin/env python3
"""Build a self-contained, plug-and-play binary for the current platform.

Outputs:
    Linux:   dist/video-extender                 (single file, +x)
    macOS:   dist/Video Extender.app             (.app bundle)
    Windows: dist/video-extender.exe             (single file)

The output bundles:
    - Python interpreter
    - PySide6 (Qt 6) runtime
    - ffmpeg + ffprobe static binaries
    - The entire video_extender package

End user just downloads the artifact for their OS and double-clicks. No Python,
no pip, no venv, no internet required after download.

Usage:
    python build.py [--clean]

Cross-platform: each OS must run this on its own machine (or via CI). PyInstaller
does not cross-compile.
"""
from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BUILD_VENV = ROOT / ".venv-build"
DIST = ROOT / "dist"
BUILD_TMP = ROOT / "build"
SPEC_FILE = ROOT / "video-extender.spec"


def _venv_python() -> Path:
    if platform.system() == "Windows":
        return BUILD_VENV / "Scripts" / "python.exe"
    return BUILD_VENV / "bin" / "python"


def _venv_pip() -> Path:
    if platform.system() == "Windows":
        return BUILD_VENV / "Scripts" / "pip.exe"
    return BUILD_VENV / "bin" / "pip"


def _import_run() -> object:
    """Load run.py as a module so we reuse its ffmpeg/Python helpers."""
    from importlib.util import module_from_spec, spec_from_file_location
    spec = spec_from_file_location("run_helpers", ROOT / "run.py")
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load run.py helpers")
    mod = module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _ensure_build_venv() -> Path:
    """Create the build venv with PyInstaller + PySide6 installed."""
    if _venv_python().exists():
        return _venv_python()

    run = _import_run()
    python = run._choose_python_for_venv()  # type: ignore[attr-defined]

    print(f">> Creating build venv at {BUILD_VENV}")
    subprocess.check_call([python, "-m", "venv", str(BUILD_VENV)])
    subprocess.check_call(
        [str(_venv_pip()), "install", "--upgrade", "pip", "--quiet"]
    )
    print(">> Installing PyInstaller + PySide6 + project")
    subprocess.check_call([
        str(_venv_pip()), "install", "--quiet",
        "pyinstaller>=6.0",
        "PySide6>=6.6.0",
    ])
    # Install our project so PyInstaller can `import video_extender`.
    subprocess.check_call([
        str(_venv_pip()), "install", "--quiet", "-e", str(ROOT),
    ])
    return _venv_python()


def _ensure_ffmpeg_bundle() -> tuple[Path, Path]:
    """Make sure ffmpeg + ffprobe are present in ROOT/.ffmpeg/, return paths."""
    run = _import_run()
    ffmpeg, ffprobe = run._download_bundled_ffmpeg()  # type: ignore[attr-defined]
    print(f">> Bundling ffmpeg:  {ffmpeg}")
    print(f">> Bundling ffprobe: {ffprobe}")
    return ffmpeg, ffprobe


def _write_spec(ffmpeg: Path, ffprobe: Path) -> Path:
    """Generate the PyInstaller .spec file. We hand-write it (instead of using
    CLI args) so we can declare PySide6 hidden imports and Qt plugin handling
    explicitly — those are notorious sources of "works on dev, fails on user".
    """
    is_windows = platform.system() == "Windows"
    is_macos = platform.system() == "Darwin"

    # Use forward slashes inside the spec (Python literal); PyInstaller handles both.
    ffmpeg_str = str(ffmpeg).replace("\\", "/")
    ffprobe_str = str(ffprobe).replace("\\", "/")
    icon_arg = ""  # add platform icon files later if desired

    binaries_block = (
        f"binaries=[\n"
        f"    (r'{ffmpeg_str}', '.'),\n"
        f"    (r'{ffprobe_str}', '.'),\n"
        f"]"
    )

    spec = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build.py — do not edit by hand.
block_cipher = None

a = Analysis(
    ['src/video_extender/__main__.py'],
    pathex=['src'],
    {binaries_block},
    datas=[],
    hiddenimports=[
        'PySide6.QtCore', 'PySide6.QtGui', 'PySide6.QtWidgets',
        # Auto-discovery imports (registered via __init_subclass__):
        'video_extender.core.encoders.amf',
        'video_extender.core.encoders.libaom_av1',
        'video_extender.core.encoders.libvpx_vp9',
        'video_extender.core.encoders.libx264',
        'video_extender.core.encoders.libx265',
        'video_extender.core.encoders.nvenc',
        'video_extender.core.encoders.qsv',
        'video_extender.core.encoders.vaapi',
        'video_extender.core.encoders.videotoolbox',
        'video_extender.core.extenders.black',
        'video_extender.core.extenders.freeze',
        'video_extender.core.extenders.image_card',
        'video_extender.core.extenders.intro_outro',
        'video_extender.core.extenders.loop',
        'video_extender.core.filters.aspect_convert',
        'video_extender.core.filters.audio_fade_out',
        'video_extender.core.filters.audio_normalize',
        'video_extender.core.filters.color_grade',
        'video_extender.core.filters.metadata_strip',
        'video_extender.core.filters.subtitle_burn',
        'video_extender.core.filters.watermark',
        'video_extender.core.presets.linkedin',
        'video_extender.core.presets.meta',
        'video_extender.core.presets.tiktok',
        'video_extender.core.presets.twitter',
        'video_extender.core.presets.youtube',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        # Cut PySide6 modules we never import — shaves ~80–150 MB.
        'PySide6.QtWebEngine', 'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets',
        'PySide6.Qt3DCore', 'PySide6.Qt3DRender', 'PySide6.QtCharts',
        'PySide6.QtDataVisualization', 'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets', 'PySide6.QtQuick', 'PySide6.QtQuick3D',
        'PySide6.QtQml', 'PySide6.QtPdf', 'PySide6.QtPdfWidgets',
        'PySide6.QtSql', 'PySide6.QtTest',
        # pytest etc. accidentally pulled in by editable install metadata
        'pytest', 'pillow', 'PIL',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='video-extender',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console={'True' if not (is_windows or is_macos) else 'False'},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    {icon_arg}
)
"""
    if is_macos:
        spec += """
app = BUNDLE(
    exe,
    name='Video Extender.app',
    icon=None,
    bundle_identifier='com.video-extender.app',
    info_plist={
        'CFBundleName': 'Video Extender',
        'CFBundleDisplayName': 'Video Extender',
        'CFBundleShortVersionString': '0.1.0',
        'NSHighResolutionCapable': True,
    },
)
"""
    SPEC_FILE.write_text(spec, encoding="utf-8")
    return SPEC_FILE


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build standalone video-extender binary")
    ap.add_argument("--clean", action="store_true",
                    help="Wipe build/, dist/, and the build venv before building.")
    args = ap.parse_args(argv)

    if args.clean:
        for p in (DIST, BUILD_TMP, BUILD_VENV, SPEC_FILE):
            if p.exists():
                print(f">> Removing {p}")
                if p.is_file():
                    p.unlink()
                else:
                    shutil.rmtree(p, ignore_errors=True)

    python = _ensure_build_venv()
    ffmpeg, ffprobe = _ensure_ffmpeg_bundle()
    spec = _write_spec(ffmpeg, ffprobe)

    print(">> Running PyInstaller")
    subprocess.check_call(
        [str(python), "-m", "PyInstaller", "--noconfirm", str(spec)],
        cwd=str(ROOT),
    )

    # Locate the produced artifact and rename to platform-tagged file.
    system = platform.system().lower()
    arch = platform.machine().lower()
    if platform.system() == "Windows":
        produced = DIST / "video-extender.exe"
        final = DIST / f"video-extender-{system}-{arch}.exe"
    elif platform.system() == "Darwin":
        produced = DIST / "Video Extender.app"
        final = DIST / f"Video-Extender-{system}-{arch}.app"
    else:
        produced = DIST / "video-extender"
        final = DIST / f"video-extender-{system}-{arch}"

    if produced.exists() and produced != final:
        if final.exists():
            if final.is_file():
                final.unlink()
            else:
                shutil.rmtree(final)
        produced.rename(final)
        if platform.system() != "Windows" and final.is_file():
            os.chmod(final, 0o755)
        print(f"\n✓ Build OK: {final}")
        size_mb = (
            sum(f.stat().st_size for f in final.rglob("*") if f.is_file()) / 1024**2
            if final.is_dir() else final.stat().st_size / 1024**2
        )
        print(f"  Size: {size_mb:.1f} MB")
    else:
        print(f"\n? Build artifact: {produced}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
